export const employessCard = [
    {employeeName: "cardName1", prof: "cardProf1", level: "condition1", img: "em1"},
    {employeeName: "cardName2", prof: "cardProf2", level: "condition2", img: "em12"},
    {employeeName: "cardName3", prof: "cardProf3", level: "condition3", img: "em2"},
    {employeeName: "cardName4", prof: "cardProf4", level: "condition4", img: "em13"},
    {employeeName: "cardName5", prof: "cardProf5", level: "condition5", img: "em8"},
    {employeeName: "cardName6", prof: "cardProf6", level: "condition6", img: "em14"},
    {employeeName: "cardName7", prof: "cardProf7", level: "condition7", img: "em4"},
    {employeeName: "cardName8", prof: "cardProf8", level: "condition8", img: "em15"},
    {employeeName: "cardName9", prof: "cardProf9", level: "condition9", img: "em5"},
    {employeeName: "cardName10", prof: "cardProf10", level: "condition10", img: "em16"},
    {employeeName: "cardName11", prof: "cardProf11", level: "condition11", img: "em6"},
    {employeeName: "cardName12", prof: "cardProf12", level: "condition12", img: "em17"},
    {employeeName: "cardName13", prof: "cardProf13", level: "condition13", img: "em3"},
    {employeeName: "cardName14", prof: "cardProf14", level: "condition14", img: "em18"},
    {employeeName: "cardName15", prof: "cardProf15", level: "condition15", img: "em3"},
    {employeeName: "cardName16", prof: "cardProf16", level: "condition16", img: "em19"},
    {employeeName: "cardName17", prof: "cardProf17", level: "condition17", img: "em9"},
    {employeeName: "cardName18", prof: "cardProf18", level: "condition18", img: "em20"},
    {employeeName: "cardName19", prof: "cardProf19", level: "condition19", img: "em10"},
    {employeeName: "cardName20", prof: "cardProf20", level: "condition20", img: "em21"},
    {employeeName: "cardName21", prof: "cardProf21", level: "condition21", img: "em11"},
]