export const newsCards = [
  { title: "cards1Title", description: "description1", date: "date1", img: "news1" },
  { title: "cards10Title", description: "description10", date: "date10", img: "news10" },

  { title: "cards11Title", description: "description11", date: "date11", img: "news11" },
  { title: "cards12Title", description: "description12", date: "date12", img: "news12" },
  { title: "cards13Title", description: "description13", date: "date13", img: "news13" },
  { title: "cards14Title", description: "description14", date: "date14", img: "news14" },
  { title: "cards15Title", description: "description15", date: "date15", img: "news15" },
  { title: "cards16Title", description: "description16", date: "date16", img: "news16" },
  { title: "cards17Title", description: "description17", date: "date17", img: "news17" },
  { title: "cards18Title", description: "description18", date: "date18", img: "news18" },
  { title: "cards19Title", description: "description19", date: "date19", img: "news19" },
  { title: "cards20Title", description: "description20", date: "date20", img: "news20" },

  { title: "cards21Title", description: "description21", date: "date21", img: "news21" },
  { title: "cards22Title", description: "description22", date: "date22", img: "news22" },
  { title: "cards23Title", description: "description23", date: "date23", img: "news23" },
  { title: "cards24Title", description: "description24", date: "date24", img: "news24" },
  { title: "cards25Title", description: "description25", date: "date25", img: "news25" },
  { title: "cards26Title", description: "description26", date: "date26", img: "news26" },
  { title: "cards27Title", description: "description27", date: "date27", img: "news27" },
  { title: "cards28Title", description: "description28", date: "date28", img: "news28" },
  { title: "cards29Title", description: "description29", date: "date29", img: "news29" },
  { title: "cards30Title", description: "description30", date: "date30", img: "news30" },

  { title: "cards31Title", description: "description31", date: "date31", img: "news31" },
  { title: "cards32Title", description: "description32", date: "date32", img: "news32" },
  { title: "cards33Title", description: "description33", date: "date33", img: "news33" },
  { title: "cards34Title", description: "description34", date: "date34", img: "news34" },
  { title: "cards35Title", description: "description35", date: "date35", img: "news35" },
  { title: "cards36Title", description: "description36", date: "date36", img: "news36" },
  { title: "cards37Title", description: "description37", date: "date37", img: "news37" },
  { title: "cards38Title", description: "description38", date: "date38", img: "news38" },
  { title: "cards39Title", description: "description39", date: "date39", img: "news39" },
  { title: "cards40Title", description: "description40", date: "date40", img: "news40" },

  { title: "cards41Title", description: "description41", date: "date41", img: "news41" },
  { title: "cards42Title", description: "description42", date: "date42", img: "news42" },
  { title: "cards43Title", description: "description43", date: "date43", img: "news43" },
  { title: "cards44Title", description: "description44", date: "date44", img: "news44" },
  { title: "cards45Title", description: "description45", date: "date45", img: "news45" },
  { title: "cards46Title", description: "description46", date: "date46", img: "news46" },
  { title: "cards47Title", description: "description47", date: "date47", img: "news47" },
  { title: "cards48Title", description: "description48", date: "date48", img: "news48" },
  { title: "cards49Title", description: "description49", date: "date49", img: "news49" },
  { title: "cards50Title", description: "description50", date: "date50", img: "news50" },

  { title: "cards51Title", description: "description51", date: "date51", img: "news51" },
  { title: "cards52Title", description: "description52", date: "date52", img: "news52" },
  { title: "cards53Title", description: "description53", date: "date53", img: "news53" },
  { title: "cards54Title", description: "description54", date: "date54", img: "news54" },
  { title: "cards55Title", description: "description55", date: "date55", img: "news55" },
  { title: "cards56Title", description: "description56", date: "date56", img: "news56" },
  { title: "cards57Title", description: "description57", date: "date57", img: "news57" },
  { title: "cards58Title", description: "description58", date: "date58", img: "news58" },
  { title: "cards59Title", description: "description59", date: "date59", img: "news59" },
  { title: "cards60Title", description: "description60", date: "date60", img: "news60" },

  { title: "cards61Title", description: "description61", date: "date61", img: "news61" },
  { title: "cards62Title", description: "description62", date: "date62", img: "news62" },
  { title: "cards63Title", description: "description63", date: "date63", img: "news63" },
  { title: "cards64Title", description: "description64", date: "date64", img: "news64" },
  { title: "cards65Title", description: "description65", date: "date65", img: "news65" },
  { title: "cards66Title", description: "description66", date: "date66", img: "news66" },
  { title: "cards67Title", description: "description67", date: "date67", img: "news67" },
  { title: "cards68Title", description: "description68", date: "date68", img: "news68" },
  { title: "cards69Title", description: "description69", date: "date69", img: "news69" },
  { title: "cards70Title", description: "description70", date: "date70", img: "news70" },

  { title: "cards71Title", description: "description71", date: "date71", img: "news71" },
  { title: "cards72Title", description: "description72", date: "date72", img: "news72" },
  { title: "cards73Title", description: "description73", date: "date73", img: "news73" },
  { title: "cards74Title", description: "description74", date: "date74", img: "news74" },
  { title: "cards75Title", description: "description75", date: "date75", img: "news75" },
  { title: "cards76Title", description: "description76", date: "date76", img: "news76" },
  { title: "cards77Title", description: "description77", date: "date77", img: "news77" },
  { title: "cards78Title", description: "description78", date: "date78", img: "news78" },
  { title: "cards79Title", description: "description79", date: "date79", img: "news79" },
  { title: "cards80Title", description: "description80", date: "date80", img: "news80" },

  
];
